### ISSUE TITLE
EnumAccessor quietly overrides existing methods

### ISSUE THREAD

**Issue by tlaferriere** [valsteen/sort_by_derive#10]
While adding tests to the crate, I have uncovered a hygiene bug in the `EnumAccessor`. It passes compilation for accessors whose name conflicts with existing methods. Here is an example that should give a compilation error, but compiles successfully.
```rust
use sort_by_derive::EnumAccessor;

#[derive(EnumAccessor)]
#[accessor(a: u16, except(Variant3))]
#[accessor(b: u32, except(Variant1,Variant2))]
enum E {
    Variant1 { a: u16 },
    Variant2 { a: u16, c: u32 },
    Variant3 { b: u32 },
}

impl E {
    fn b(&self) {}
}

fn main() {}
```
The problem arises from the fact that the accessors are implemented in a generated trait. Due to the way that traits work in Rust, the generated trait does not conflict with any of the predefined methods, be it in the struct `impl` or other traits that do not conflict with the generated trait.
When the enum is `use`d from another module, this isn't an issue, as you would have to explicitly bring that trait into the scope. This also sheds light on the fact that this trait is not documented as clearly as it is for the `EnumSequence` generated trait.

**Comment by valsteen** [comment]
👀 nice finding

This is nasty in combination with SortBy – it compiles fine but the call to `b()` is really just a Unit type, making the sort criteria pointless.

```rust
#[derive(EnumAccessor, SortBy)]
#[sort_by(a(), b())]
#[accessor(a: u16, except(Variant3))]
#[accessor(b: u32, except(Variant1, Variant2))]
enum E {
    Variant1 { a: u16 },
    Variant2 { a: u16, c: u32 },
    Variant3 { b: u32 },
}

impl E {
    fn b(&self) {}
}
```

the only hint we get comes from clippy:

```rust
error: this call to `hash` on the unit type will do nothing
 --> src/main.rs:6:16
  |
6 | #[sort_by(a(), b())]
  |                ^ help: remove the call to `hash` or consider using: `0_u8.hash(b)`
  |
  = note: the implementation of `Hash` for `()` is a no-op
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_hash
  = note: `#[deny(clippy::unit_hash)]` on by default
```

I suppose the most footgun-proof solution is to let the compilation fail as you suggest.

There might be some trick to generate some code that will fail at compile time if collision exists. Hopefully something like this is possible:

```rust
// dummy function generated by EnumAccessor
fn generated_dummy_function() {
    // something that fails at compile time if EAccessor::b and E::b both exists
    // if possible the associated span should highlight `accessor(b: u32, except(Variant1, Variant2)`
    // with a relevant message 
}
```

**Comment by valsteen** [comment]
Hi, as it turns out, I used an extension trait because I thought only one `impl` block was allowed ... but it's allowed to have several impl blocks. See

- #12

**Comment by valsteen** [comment]
Hi, on my side I think this works now and I'd like to close this issue to avoid confusing users, please re-open or create a follow-up issue if you think there is a remaining problem
